<?php $this->breadcrumbs(array('title' => '系统管理', 'url' => ''), array('title' => '账号列表', 'url' => '/account/'), array('title' => '添加账号', 'url' => ''))?>

<script type="text/javascript">
var isClick = 0;
function add()
{
    if (isClick === 1) {
        return false;
    }
    isClick = 1;
    
    var post = {};
    
    post['account'] = $.trim($("#account").val());
    if (post['account'].length <= 0) {
        alert("请输入登陆账号");
        isClick = 0;
        return false;
    }

    post['password'] = $.trim($("#passwd").val());
    if (post['password'].length <= 0) {
        alert("请输入登陆密码");
        isClick = 0;
        return false;
    }
    if (post['password'].length > 20) {
        alert("登陆密码最多20个字符");
        isClick = 0;
        return false;
    }
    
    post['realname'] = $.trim($("#realname").val());
    if (post['realname'].length <= 0) {
        alert("请输入真实姓名");
        isClick = 0;
        return false;
    }
    
    post['roleList'] = [];
    $('input[name=role]').each(function(){
        if (this.checked) {
            post['roleList'].push(this.value);
        }
    });
    
    post['phone'] = $.trim($("#phone").val());
    post['email'] = $.trim($("#email").val());
    
    $.post('/admin/user/add', post, function(result){
        if (parseInt(result.status) === 0) {
            alert('添加成功');
            window.location.href = '/admin/user/';
        } else {
            isClick = 0;
            alert(result.msg);
        }
    }, 'json');
}
</script>

<div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">添加账号</div>
    <div class="panel-body">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-7">
                    <form class="form-horizontal" role="form">
                    <div class="form-group">
                        <label for="accountId" class="col-sm-2 control-label resetPadding">登陆账号</label>
                        <div class="col-sm-10">
                          <input type="text" class="PROGRAM-txt form-control" name="account" id="accountId" placeholder="请输入你的登陆账号">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="passwdId" class="col-sm-2 control-label resetPadding">登陆密码</label>
                        <div class="col-sm-10">
                          <input type="text" class="PROGRAM-txt form-control" name="passwd" id="passwdId" placeholder="请输入你的登陆密码">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="realnameId" class="col-sm-2 control-label resetPadding">真实姓名</label>
                        <div class="col-sm-10">
                          <input type="text" class="PROGRAM-txt form-control" name="realname" id="realnameId" placeholder="请输入你的真实姓名">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="contactPhoneId" class="col-sm-2 control-label resetPadding">联系电话</label>
                        <div class="col-sm-10">
                          <input type="text" class="PROGRAM-txt form-control" name="contact_phone" id="contactPhoneId" placeholder="请输入你的联系电话">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="contactEmailId" class="col-sm-2 control-label resetPadding">联系邮箱</label>
                        <div class="col-sm-10">
                          <input type="text" class="PROGRAM-txt form-control" name="contact_email" id="contactEmailId" placeholder="请输入你的联系邮箱">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-12">
                            <button type="submit" class="btn btn-success" style='padding:5px 12px'>提交</button>
                        </div>
                    </div>
                    </form>
                </div>
                <div class="col-sm-5">
                    dfdsf
                </div>
            </div>
        </div>
    </div>
</div>