<?php echo $this->breadcrumbs(array('title' => '系统管理', 'url' => ''), array('title' => '账号列表', 'url' => ''))?>

<div class="panel panel-default">
    <div class="panel-heading">按条件搜索</div>
    <div class="panel-body">
        <form method="POST" id="searchForm" action="/account/" class="form-horizontal" role="form">
            <div class="form-group">
                <label class="col-sm-2 control-label width-rem-10">筛选：</label>
                <div class="col-sm-10">
                    <select class="form-control form-inline width-rem-15" id="searchTypeId" name="searchType" onchange="schange(this);return false;">
                        <option value="account" <?php if($this->searchs['searchType'] === 'account'):?>selected<?php endif?>>登录账号</option>
                        <option value="realname" <?php if($this->searchs['searchType'] === 'realname'):?>selected<?php endif?>>用户名</option>
                    </select>
                    <input type="hidden" id="statusId" name="status" value="<?php echo $this->searchs['status']?>" />
                    <input type="text" class="form-control form-inline width-rem-40" id="searchValue" placeholder="输入查询条件" value="<?php echo $this->searchs['searchValue']?>">
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label width-rem-10">状态：</label>
                <div class="col-sm-10">
                    <label class="radio-inline">
                        <input type="radio" name="statusShow" id="inlineRadio1" value="99" <?php echo (intval($this->searchs['status']) === 99) ? 'checked' : '' ?>> 全部
                    </label>
                    <label class="radio-inline">
                        <input type="radio" name="statusShow" id="inlineRadio2" value="1" <?php echo (intval($this->searchs['status']) === 1) ? 'checked' : '' ?>> 正常
                    </label>
                    <label class="radio-inline">
                        <input type="radio" name="statusShow" id="inlineRadio3" value="2" <?php echo (intval($this->searchs['status']) === 2) ? 'checked' : '' ?>> 锁定
                    </label>
                </div>
            </div>
            <div class="form-group">
                <div class="offsetLT-rem-4">
                    <button type="button" class="btn btn-default" onclick="query();">开始搜索</button>&nbsp;&nbsp;
                    <button type="button" class="btn btn-default" onclick="cancelQuery();">取消搜索</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">账号列表<a href="/account/add" class="btn btn-default pull-right">添加账号</a></div>

    <!-- Table -->
    <table class="table tablesorter">
        <thead>
          <tr>
            <th>用户ID</th>
            <th>账号</th>
            <th>姓名</th>
            <th>电话</th>
            <th>邮箱</th>
            <th>状态</th>
            <th>创建时间</th>
            <th>操作</th> 
          </tr>
        </thead>
        <tbody>
            <?php if($this->list->itemTotal() > 0):?>
                <?php foreach($this->list as $v):?>
                    <tr id="item_<?php echo $v['userid']?>"> 
                        <td><?php echo $v['userid']?></td> 
                        <td><?php echo $v['account']?></td> 
                        <td><?php echo $v['realname']?></td>
                        <td><?php echo $v['contactPhone']?></td>
                        <td><?php echo $v['contactEmail']?></td> 
                        <td><?php echo (!$v['___isLock'])?'正常':'锁定'?></td> 
                        <td><?php echo date('Y-m-d H:i:s', $v['createTime'])?></td> 
                        <td>
                            <?php if($v['___isSuperAdmin']):?>
                                <a href="/account/edit/userid/<?php echo $v['userid']?>">编辑</a>&nbsp;
                                <?php if(intval($this->searchs['status']) === 99):?>
                                        <a href="###" id="lock_<?php echo $v['userid']?>" onclick="lock(<?php echo $v['userid']?>);return false;" style="display:<?php if(intval($v['status']) === 1):?>inline-block<?php else:?>none<?php endif?>;">锁定</a>
                                        <a href="###" id="unlock_<?php echo $v['userid']?>" onclick="unlock(<?php echo $v['userid']?>);return false;" style="display:<?php if(intval($v['status']) === 2):?>inline-block<?php else:?>none<?php endif?>;">解锁</a>
                                <?php else:?>
                                    <?php if(intval($v['status']) === 1):?>
                                        <a href="###" onclick="lock(<?php echo $v['userid']?>);return false;">锁定</a>
                                    <?php elseif(intval($v['status']) === 2):?>
                                        <a href="###" onclick="unlock(<?php echo $v['userid']?>);return false;">解锁</a>
                                    <?php endif?>
                                <?php endif?>
                            <?php endif?>
                        </td>
                    </tr> 
                <?php endforeach?>
            <?php endif?>
        </tbody>
    </table>
    <?php if($this->list->itemTotal() > 0):?>
        <div class="table-page"><?php echo $this->list?></div>
    <?php endif?>
</div>

<script>
function cancelQuery()
{
    window.location.href = "/account/";
}
function query() 
{
    var searchType = $('#searchTypeId').val();
    switch (searchType) {
        case 'account':
            $('#searchValueId').val($.trim($("#accountId").val()));
            break;
        case 'realname':
            var realname = $.trim($("#realnameId").val());
            $('#searchValueId').val(realname);
            break;
    }
    $('#statusId').val($.trim($("input[name=statusShow]:checked").val()));
    $('#searchForm').submit();
}
function schange(self)
{
    var id = self.value;
    $('.PROGRAM-v').hide();
    $('#'+id+'BoxId').show();
}
function lock(userid) 
{
    if (window.confirm('确定要锁定吗？')) {
        var divId = '#item_' + userid;
        $.post('/account/lock/', {userid: userid}, function(result) {
            if (parseInt(result.status) === 0) {
                <?php if(intval($this->searchs['status']) === 99):?>
                    $('#lock_'+userid).css('display', 'none');
                    $('#unlock_'+userid).css('display', 'inline-block');
                <?php else:?>
                    $(divId).remove();
                <?php endif?>
                alert('锁定成功');
            } else {
                alert('锁定失败');
            }
        }, 'json');
    }
}
function unlock(userid) 
{
    if (window.confirm('确定要解锁吗？')) {
        var divId = '#item_' + userid;
        $.post('/account/unlock/', {userid: userid}, function(result) {
            if (parseInt(result.status) === 0) {
                <?php if(intval($this->searchs['status']) === 99):?>
                    $('#unlock_'+userid).css('display', 'none');
                    $('#lock_'+userid).css('display', 'inline-block');
                <?php else:?>
                    $(divId).remove();
                <?php endif?>
                alert('解锁成功');
            } else {
                alert('解锁失败');
            }
        }, 'json');
    }
}
</script>