<?php 
$this->headLink()->appendStylesheet($this->assetPath()->getCssOfPage('project_code_index'));
$this->breadcrumbs(array('title' => '项目管理', 'url' => ''), array('title' => $this->projectInfo['name'], 'url' => $this->projectInfo['pageUrl']), array('title' => '代码管理', 'url' => ''));
?>

<!-- 导航 -->
<?php echo $this->render('project/_slot/nav')?>

<!-- 可查阅分支 -->
<?php if($this->currentUseBranch !== 'Branch')://待初始化仓库?>
<div class="btn-group">
    <button type="button" class="btn dropdown-toggle btn-noborder" data-toggle="dropdown" aria-expanded="false"><?php echo $this->currentUseBranch?>&nbsp;<span class="caret"></span></button>
    <ul class="dropdown-menu dropdown-theme-gray arrow-up" role="menu">
      <?php foreach($this->branchList as $v):?>
        <?php 
            if($this->currentUseBranch == $v['___showType']) {
                $active   = "active";
                $iconShow = 'inline-block';
            } else {
                $active   = "";
                $iconShow = 'none';
            }
        ?>
        <li class="<?php echo $active?>">
            <a href="#">
                <?php echo $v['___showType']?>
                <span class="ml-10px mr-10px"><?php echo $v['name']?></span><i class="glyphicon glyphicon-ok fr" style="display:<?php echo $iconShow?>"></i>
            </a>
        </li>
      <?php endforeach?>
    </ul>
</div>
<?php endif?>
<?php if ($this->loginUserInfo['___isSuperAdmin'])://超级管理员?>
<button type="button" id="createRepoBtnId" class="btn btn-success btn-theme-small ml-20px">创建仓库</button>
<?php endif?>
<hr/>

<!-- 分支的内容 -->
<?php if($this->currentUseBranch !== 'Branch')://待初始化仓库?>
<div class="row">
    <div class="col-sm-3 plr-1px" id="commitListId" style="border-right:1px solid #ddd">
        <?php if(count($this->history['list']) > 0):?>
        <div><h4>History <span class="badge"><?php echo $this->history['total']?></span></h4><hr/></div>
        <ul class="PROGRAM-commitbox list-group">
            <?php foreach($this->history['list'] as $k=>$v):?>
                <li class="PROGRAM-commitbtn list-group-item list-noborder <?php if($k===0):?>active<?php endif?>" data-cmid="<?php echo $v['commitId']?>">
                    <div class="licon"><img src="<?php echo $this->assetPath()->getImage('common/default.jpg')?>" /></div>
                    <div class="rcon">
                        <span style="display: -webkit-inline-box;-webkit-box-orient: vertical;-webkit-line-clamp: 1;overflow: hidden;"><?php echo $v['message']?></span>
                        <br/>
                        <span style="color:#ccc"><?php echo date('Y-m-d', $v['date'])?></span>
                        <i>by</i>&nbsp;<?php echo $v['author']?>
                    </div>
                </li>
            <?php endforeach?>
        </ul>
        <?php endif?>
    </div>
    <div class="col-sm-9 plr-1px" id="commitContentListId">
        <?php if(count($this->commitContentList['list']) > 0):?>
        <ul id="commitContentListBoxId" class="list-group">
            <?php foreach($this->commitContentList['list'] as $v):?>
                <li class="PROGRAM-commitconBtn list-group-item list-noborder" data-cmid="<?php echo $this->commitContentList['commitIdHash']?>" data-bl="<?php echo $v['statistics']['beginLineNum']?>" data-el="<?php echo $v['statistics']['endLineNum']?>" data-way="right">
                    <span style="display: -webkit-inline-box;-webkit-box-orient: vertical;-webkit-line-clamp: 1;overflow: hidden;"><i class="icon-caret-right mr-5px"></i><?php echo $v['name']?></span>
                    <span class="fr">
                        <?php echo $v['statistics']['total']?>
                        <?php for($i=0;$i<$v['statistics']['insertionsBlock'];$i++):?><b style="width:5px;height:5px;background:#00B83F;display: inline-block;"></b> <?php endfor?>
                        <?php for($i=0;$i<$v['statistics']['deletionBlock'];$i++):?><b style="width:5px;height:5px;background:#D20009;display: inline-block;"></b> <?php endfor?>
                        <?php for($i=0;$i<$v['statistics']['normalBlock'];$i++):?><b style="width:5px;height:5px;background:#ccc;display: inline-block;"></b> <?php endfor?>
                    </span>
                    <div></div>
                </li>
            <?php endforeach?>
        </ul>
        <?php endif?>
    </div>
</div>
<?php elseif(!empty($this->repoInfo)):?>
<div id="debugBoxId" class="panel panel-default">
    <div class="panel-heading"><i class="icon-question-sign mr-5px"></i>快速帮助</div>
    <div class="panel-body">
        <div class="mb-10px">克隆当前仓库 不知道如何操作？访问 此处 查看帮助！</div>
        <div>
            <div class="input-group">
                <span class="PROGRAM-repopath_switch input-group-addon blue-border" data-rp="<?php echo $this->repoInfo['___showHTTPPath']?>">HTTP</span>
                <span class="PROGRAM-repopath_switch input-group-addon" data-rp="<?php echo $this->repoInfo['___showSSHPath']?>">SSH</span>
                <input type="text" class="form-control" id="repoPath" value="<?php echo $this->repoInfo['___showHTTPPath']?>" />
            </div>
        </div>
        <hr/>
        <div>
            从命令行创建一个新的仓库
<pre class="mt-10px">
touch README.md
git init
git add README.md
git commit -m "first commit"
<span class="PROGRAM-repopath_txt">git remote add origin <?php echo $this->repoInfo['___showHTTPPath']?></span>
git push -u origin master
</pre>
        </div>
        <hr/>
        <div>
            从命令行推送已经创建的仓库
<pre class="mt-10px">
<span class="PROGRAM-repopath_txt">git remote add origin <?php echo $this->repoInfo['___showHTTPPath']?></span>
git push -u origin master
</pre>
        </div>
    </div>
</div>
<?php endif?>

<script id='commitContentListTmplId'  type='text/x-jquery-tmpl'>
    {{each(i, cc) commitContentList}}
    <li class="PROGRAM-commitconBtn list-group-item list-noborder" data-cmid="${commitIdHash}" data-bl="${cc.statistics.beginLineNum}" data-el="${cc.statistics.endLineNum}" data-way="right">
        <span style="display: -webkit-inline-box;-webkit-box-orient: vertical;-webkit-line-clamp: 1;overflow: hidden;"><i class="icon-caret-right mr-5px"></i>${cc.name}</span>
        <span class="fr">
            ${cc.statistics.total}
            {{html cc.greenBlock}}{{html cc.redBlock}}{{html cc.grayBlock}}
        </span>
        <div></div>
    </li>
    {{/each}}
</script>

<!-- 创建仓库 -->
<div class="modal fade" id="createRepoBoxId" tabindex="-1" role="dialog" aria-labelledby="contextMenuModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">创建 <b>“<?php echo $this->projectInfo['name']?>”</b> 新仓库</h4>
            </div>
            <div class="modal-body">
                <form id="repoFormId" class="form-horizontal" role="form">
                    <div class="form-group">
                        <label for="nameId" class="col-sm-1 control-label resetPadding padd-top-7 width-13">仓库名称</label>
                        <div class="col-sm-10">
                            <input type="text" class="PROGRAM-txt form-control" name="name" id="nameId" placeholder="请输入仓库名称，仅允许英文+下划线，且尽量短而有意义">
                            <span class="PROGRAM-inputerror glyphicon glyphicon-remove form-control-feedback"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="introId" class="col-sm-1 control-label resetPadding padd-top-7 width-13">仓库描述</label>
                        <div class="col-sm-10">
                            <textarea id="introId" name="intro" class="PROGRAM-txt form-control" rows="3" placeholder="请输入仓库描述"></textarea>
                            <span class="PROGRAM-inputerror glyphicon glyphicon-remove form-control-feedback"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="orgId" class="col-sm-1 control-label resetPadding padd-top-7 width-13">所属组织</label>
                        <div class="col-sm-10">
                            <?php if(count($this->orgList) > 0):?>
                                <?php foreach($this->orgList as $v):?>
                                    <label class="radio-inline">
                                        <input type="radio" name="org" id="org<?php echo $v['id']?>" value="<?php echo $v['id']?>"> <?php echo $v['zname']?>
                                    </label>
                                <?php endforeach?>
                            <?php else:?>
                                请先创建组织
                            <?php endif?>
                            <span id="orgErrorId" class="PROGRAM-inputerror glyphicon glyphicon-remove form-control-feedback"></span>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                <button type="button" class="btn btn-primary" id="repoCreateBtnId">提交</button>
            </div>
        </div>
    </div>
</div>

<script>
var projectId = <?php echo $this->projectInfo['id']?>;
__wait(function(){
    $('#commitListId').equalHeight($('#menuId').height() - 135);
    $('#commitContentListId').equalHeight($('#menuId').height() - 135);
    
    $('.PROGRAM-repopath_switch').on('click', function(){
        var repoPath = $(this).data('rp');
        $('.PROGRAM-repopath_switch').removeClass('blue-border');
        $(this).addClass('blue-border');
        $('#repoPath').val(repoPath);
        $('.PROGRAM-repopath_txt').html('git remote add origin '+repoPath);
    });
    
    //创建仓库中的文本框自动聚焦
    $('#createRepoBoxId').on('shown.bs.modal', function () 
    {
        $('#title', this).focus();
    });
    //显示创建仓库弹层
    $('#createRepoBtnId').on('click', function(e) 
    {
        $('#repoFormId').get(0).reset();
        var repoModalDom = $('#createRepoBoxId');
        repoModalDom.modal('show');
    });
    //提交创建仓库
    var formObj = {
        'name' : $('#nameId'),
        'intro' : $('#introId'),
        'orgError' : $('#orgErrorId')
    }
    var isRepoClick = 0;
    $('#repoCreateBtnId').on('click', function(e) 
    {
        if (isRepoClick === 1) {
            return false;
        }
        isRepoClick = 1;
        
        var post = {};
        
        post['sName'] = $.trim($('#nameId').val());
        if (post['sName'].length <= 0 || !/^[a-zA-Z_]+$/.test(post['sName'])) {
            formObj['name'].parents('.form-group').addClass('has-error has-feedback');
            formObj['name'].siblings('.PROGRAM-inputerror').show();
            formObj['name'].focus();
            isRepoClick = 0;
            return false;
        }
        
        post['sIntro'] = $.trim($('#introId').val());
        if (post['sIntro'].length <= 0) {
            formObj['intro'].parents('.form-group').addClass('has-error has-feedback');
            formObj['intro'].siblings('.PROGRAM-inputerror').show();
            formObj['intro'].focus();
            isRepoClick = 0;
            return false;
        }
        
        post['iOrgId'] = $.trim($('input[name=org]:checked').val());
        if (post['iOrgId'] == undefined || post['iOrgId'] == null || post['iOrgId'] == '') {
            formObj['orgError'].parents('.form-group').addClass('has-error has-feedback');
            formObj['orgError'].show();
            isRepoClick = 0;
            return false;
        }
        
        $.post('/project/repo/add?iProjectId='+projectId, post, function(result)
        {
            if (parseInt(result.status) === 0) {
                alert('仓库创建成功');
                $('#createRepoBoxId').modal('hide');
                $('#repoFormId').get(0).reset();
            } else {
                alert(result.msg);
            }
            isRepoClick = 0;
        }, 'json');
    });
    //获取某次提交的内容列表
    var repoPath = '<?php echo $this->repoInfo['repoPath']?>';
    var isCClick = 0;
    var currentCommitId = '<?php echo $this->currentCommitId?>';
    $('.PROGRAM-commitbtn').on('click', function()
    {
        if (isCClick === 1) {
            return false;
        }
        isCClick = 1;
        
        var commitId = $(this).data('cmid');
        if (currentCommitId === commitId) {
            isCClick = 0;
            return false;
        }
        
        currentCommitId = commitId;
        $('.PROGRAM-commitbtn').removeClass('active');
        $(this).addClass('active');
        
        $.post('/project/code/getCommitContentList?iProjectId='+projectId, {sRepoPath:repoPath, sCommitIdHash:commitId}, function(result)
        {
            if (parseInt(result.status) === 0) {
                $('#commitContentListBoxId').empty().html('');
                var list = result.data.commitContentList['list'];
                for (var k in list) {
                    var insertionsBlock = '';
                    if (list[k].statistics.insertionsBlock > 0) {
                        for (var j = 0; j < list[k].statistics.insertionsBlock; j++) {
                            insertionsBlock += '<b class="greenBlock"></b>';
                        }
                    }
                    list[k]['greenBlock'] = insertionsBlock;
                    var deletionBlock = '';
                    if (list[k].statistics.deletionBlock > 0) {
                        for (var j = 0; j < list[k].statistics.deletionBlock; j++) {
                            deletionBlock += '<b class="redBlock"></b>';
                        }
                    }
                    list[k]['redBlock'] = deletionBlock;
                    var normalBlock = '';
                    if (list[k].statistics.normalBlock > 0) {
                        for (var j = 0; j < list[k].statistics.normalBlock; j++) {
                            normalBlock += '<b class="grayBlock"></b>';
                        }
                    }
                    list[k]['grayBlock'] = normalBlock;
                }

                $('#commitContentListTmplId').tmpl({commitIdHash:result.data.commitContentList['commitIdHash'],commitContentList:list}).appendTo('#commitContentListBoxId');
            } else {
                alert(result.msg);
            }
            isCClick = 0;
        }, 'json');
    });
    
    //查看具体内容
    var isCCLClick = 0;
    $('#commitContentListBoxId').on('click', '.PROGRAM-commitconBtn', function()
    {
        if (isCCLClick === 1) {
            return false;
        }
        isCCLClick = 1;
        
        var self = $(this);
        var isOpen = self.data('isOpen');
        if (isOpen === undefined || isOpen === null || isOpen === '') {
            isOpen = 0;
        }
        if (self.data('way') === 'right') {
            self.data('way', 'down');
            $('i', self).removeClass('icon-caret-right');
            $('i', self).addClass('icon-caret-down');
            
            if (isOpen <= 0) {
                var commitId = self.data('cmid');
                var bl = self.data('bl');
                var el = self.data('el');
                $.post('/project/code/getCommitContentDiff?iProjectId='+projectId, {sRepoPath:repoPath, sCommitIdHash:commitId, iBl:bl, sEl:el}, function(result)
                {
                    if (parseInt(result.status) === 0) {
                        $('div', self).html('<pre class="code-pre">'+result.data.diffContent+'</pre>');
                    } else {
                        alert(result.msg);
                    }
                    isCCLClick = 0;
                }, 'json');
            } else {
                isCCLClick = 0;
                $('div', self).show();
            }
        } else {
            self.data('way', 'right');
            $('i', self).removeClass('icon-caret-down');
            $('i', self).addClass('icon-caret-right');
            $('div', self).hide();
            isCCLClick = 0;
            self.data('isOpen', 1);
        }
    });
});
</script>