<?php 
$this->breadcrumbs(array('title' => '平台管理', 'url' => ''), array('title' => '账号列表', 'url' => '/admin/account/'), array('title' => '编辑账号', 'url' => ''));
$this->headLink()->appendStylesheet($this->assetPath()->getCssOfModule('jquery/plugin/ztree/ztree'));
$this->script()->appendScript($this->assetPath()->getJsOfModule('jquery/plugin/ztree/ztree.min'));
?>

<div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">添加账号</div>
    <div class="panel-body">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-7">
                    <form class="form-horizontal" role="form">
                    <div class="form-group">
                        <label for="accountId" class="col-sm-2 control-label resetPadding padd-top-7">登陆账号</label>
                        <div class="col-sm-10">
                            <input type="text" class="PROGRAM-txt form-control" name="account" id="accountId" value="<?php echo $this->userInfo['account']?>" placeholder="请输入你的登陆账号">
                            <span class="PROGRAM-inputerror glyphicon glyphicon-remove form-control-feedback"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="passwdId" class="col-sm-2 control-label resetPadding padd-top-7">登陆密码</label>
                        <div class="col-sm-10">
                            <input type="text" class="PROGRAM-txt form-control" name="passwd" id="passwdId" placeholder="请输入你的登陆密码">
                            <span class="PROGRAM-inputerror glyphicon glyphicon-remove form-control-feedback"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="realnameId" class="col-sm-2 control-label resetPadding padd-top-7">真实姓名</label>
                        <div class="col-sm-10">
                            <input type="text" class="PROGRAM-txt form-control" name="realname" id="realnameId" value="<?php echo $this->userInfo['realname']?>" placeholder="请输入你的真实姓名">
                            <span class="PROGRAM-inputerror glyphicon glyphicon-remove form-control-feedback"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="contactPhoneId" class="col-sm-2 control-label resetPadding padd-top-7">联系电话</label>
                        <div class="col-sm-10">
                            <input type="text" class="PROGRAM-txt form-control" name="contact_phone" id="contactPhoneId" value="<?php echo $this->userInfo['contact_phone']?>" placeholder="请输入你的联系电话">
                            <span class="PROGRAM-inputerror glyphicon glyphicon-remove form-control-feedback"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="contactEmailId" class="col-sm-2 control-label resetPadding padd-top-7">联系邮箱</label>
                        <div class="col-sm-10">
                            <input type="text" class="PROGRAM-txt form-control" name="contact_email" id="contactEmailId" value="<?php echo $this->userInfo['contact_email']?>" placeholder="请输入你的联系邮箱">
                            <span class="PROGRAM-inputerror glyphicon glyphicon-remove form-control-feedback"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-10 col-sm-offset-2">
                            <button type="button" class="btn btn-success" style='padding:5px 12px' id="subAddId">提交</button>
                        </div>
                    </div>
                    </form>
                </div>
                <div class="col-sm-5">
                    <ul id="privilegeTree" class="ztree"></ul>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
var privilegeNodes = [];
var code;
function showCode(str) 
{
    if (!code) code = $("#code");
    code.empty();
    code.append("<li>"+str+"</li>");
}  
function getCheckTreeNodes(nodes){
    $.each(nodes, function(i,obj){
        if(obj.checked){
            privilegeNodes.push(obj.id);
            if(obj.children){
                getCheckTreeNodes(obj.children);
            }
        }
    });
}
var isClick = 0;
var formObj = {};
var userid  = '<?php echo $this->userInfo['userid']?>';
__wait(function(){
    formObj = {
        "account"       : $("#accountId"),
        "passwd"        : $("#passwdId"),
        "realname"      : $("#realnameId"),
        "contact_phone" : $("#contactPhoneId"),
        "contact_email" : $("#contactEmailId")
    };
    
    $('#subAddId').on('click', function() {
        if (isClick === 1) {
            return false;
        }
        isClick = 1;
        
        $('.PROGRAM-txt').one('keypress keyup input', function(){
            $('.form-group').removeClass('has-error').removeClass('has-feedback');
            $('.PROGRAM-inputerror').hide();
        });

        var post = {};

        post['sAccount'] = $.trim(formObj['account'].val());
        if (post['sAccount'].length <= 0) {
            formObj['account'].parents('.form-group').addClass('has-error').addClass('has-feedback');
            formObj['account'].siblings('.PROGRAM-inputerror').show();
            formObj['account'].focus();
            isClick = 0;
            return false;
        }

        var sPasswd = $.trim(formObj['passwd'].val());
        if (sPasswd.length > 0) {
            if (sPasswd.length > 20) {
                alert("登陆密码最多20个字符");
                formObj['passwd'].parents('.form-group').addClass('has-error has-feedback');
                formObj['passwd'].siblings('.PROGRAM-inputerror').show();
                formObj['passwd'].focus();
                isClick = 0;
                return false;
            }
            post['sPasswd'] = sPasswd;
        } else {
            post['sPasswd'] = '';
        }

        post['sRealname'] = $.trim(formObj['realname'].val());
        if (post['sRealname'].length <= 0) {
            formObj['realname'].parents('.form-group').addClass('has-error has-feedback');
            formObj['realname'].siblings('.PROGRAM-inputerror').show();
            formObj['realname'].focus();
            isClick = 0;
            return false;
        }
        
        post['sContactPhone'] = $.trim(formObj['contact_phone'].val());
        post['sContactEmail'] = $.trim(formObj['contact_email'].val());
        
        var zTree = $.fn.zTree.getZTreeObj("privilegeTree");
        getCheckTreeNodes(zTree.getNodes());
        if (privilegeNodes.length <= 0) {
            privilegeNodes = [];
        }
        
        post['aPrivilegeNodes'] = privilegeNodes;
        post['iUserid'] = userid;
        
        $.post('/admin/account/edit', post, function(result){
            if (parseInt(result.status) === 0) {
                alert('编辑成功');
                window.location.reload(true);
            } else {
                isClick = 0;
                alert(result.msg);
            }
        }, 'json');
    });
    
    var zNodes = <?php echo json_encode($this->menus); ?>;
    
    $.fn.zTree.init($("#privilegeTree"), {check: {enable: true},data: {simpleData: {enable: true}}}, zNodes);
    var zTree = $.fn.zTree.getZTreeObj("privilegeTree"),type = { "Y":'p' + 's', "N":'p' + 's'};
    zTree.setting.check.chkboxType = type;
    showCode('setting.check.chkboxType = { "Y" : "' + type.Y + '", "N" : "' + type.N + '" };');            

});    
</script>