<?php 
$this->breadcrumbs(array('title' => '平台管理', 'url' => ''), array('title' => '项目列表', 'url' => '/admin/project/'), array('title' => '添加项目', 'url' => ''));
?>

<div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">添加项目</div>
    <div class="panel-body">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <form class="form-horizontal" role="form">
                    <div class="form-group">
                        <label for="nameId" class="col-sm-1 control-label resetPadding padd-top-7">项目名称</label>
                        <div class="col-sm-10">
                            <input type="text" class="PROGRAM-txt form-control" name="name" id="nameId" placeholder="请输入项目名称">
                            <span class="PROGRAM-inputerror glyphicon glyphicon-remove form-control-feedback"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="introId" class="col-sm-1 control-label resetPadding padd-top-7">项目描述</label>
                        <div class="col-sm-10">
                            <textarea id="introId" name="intro" class="PROGRAM-txt form-control" rows="3" placeholder="请输入项目描述"></textarea>
                            <span class="PROGRAM-inputerror glyphicon glyphicon-remove form-control-feedback"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-10 col-sm-offset-1">
                            <button type="button" class="btn btn-success" style='padding:5px 12px' id="subAddId">提交</button>
                        </div>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
var isClick = 0;
var formObj = {};
__wait(function(){
    formObj = {
        "name" : $("#nameId"),
        "intro" : $("#introId")
    };
    
    $('#subAddId').on('click', function() {
        if (isClick === 1) {
            return false;
        }
        isClick = 1;
        
        $('.PROGRAM-txt').one('keypress keyup input', function(){
            $('.form-group').removeClass('has-error').removeClass('has-feedback');
            $('.PROGRAM-inputerror').hide();
        });

        var post = {};

        post['sName'] = $.trim(formObj['name'].val());
        if (post['sName'].length <= 0) {
            formObj['name'].parents('.form-group').addClass('has-error').addClass('has-feedback');
            formObj['name'].siblings('.PROGRAM-inputerror').show();
            formObj['name'].focus();
            isClick = 0;
            return false;
        }

        post['sIntro'] = $.trim(formObj['intro'].val());
        if (post['sIntro'].length <= 0) {
            formObj['intro'].parents('.form-group').addClass('has-error has-feedback');
            formObj['intro'].siblings('.PROGRAM-inputerror').show();
            formObj['intro'].focus();
            isClick = 0;
            return false;
        }

        $.post('/admin/project/add', post, function(result){
            if (parseInt(result.status) === 0) {
                alert('添加成功');
                window.location.href = '/admin/project/';
            } else {
                isClick = 0;
                alert(result.msg);
            }
        }, 'json');
    });      

});    
</script>