<?php echo $this->breadcrumbs(array('title' => '系统管理', 'url' => ''), array('title' => '菜单列表', 'url' => ''))?>

<div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">权限列表<a href="/privilege/add/" class="btn btn-default pull-right">添加权限</a></div>

    <!-- Table -->
    <table class="table tablesorter">
        <thead>
          <tr>
            <th class="header">权限ID</th>
            <th class="header">权限类型</th>
            <th class="header">菜单类型</th>
            <th class="header">权限名字</th>
            <th class="header">权限链接</th>
            <th class="header">权限级别</th>
            <th class="header">操作</th> 
          </tr>
        </thead>
        <tbody>
            <?php echo $this->getMenuListOfAll()?>
        </tbody>
    </table>
</div>

<script>
function del(id)
{
    if (window.confirm('确定要删除吗？')) {
        var divId = '#item_' + id;
        $.post('/privilege/del/', {iId: id}, function(result) {
            if (parseInt(result.status) === 0) {
                $('#opDel_'+id).css('display', 'none');
                $('#opRevert_'+id).css('display', 'inline-block');
                var level =  $(divId).data('l');
                if (level == 1) {
                    $(divId).css('color', '#fff');
                } else {
                    $(divId).css('color', '#eee');
                }
                alert('删除成功');
            } else {
                alert('删除失败');
            }
        }, 'json');
    }
}
function revert(id)
{
    if (window.confirm('确定要恢复吗？')) {
        var divId = '#item_' + id;
        $.post('/privilege/revert/', {iId: id}, function(result) {
            if (parseInt(result.status) === 0) {
                $('#opRevert_'+id).css('display', 'none');
                $('#opDel_'+id).css('display', 'inline-block');
                $(divId).css('color', '#333');
                alert('恢复成功');
            } else {
                alert('恢复失败');
            }
        }, 'json');
    }
}
</script>