<!doctype html> 
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title><?php echo $this->headTitle('代码管理')?></title>
        <?php 
            echo $this->headMeta('代码管理', 'keywords')->headMeta('代码管理', 'description');
            echo $this->headLink()->prependStylesheet($this->assetPath()->getCssOfModule('bootstrap/3.3.5/bootstrap.min.css,jquery/ui/base.min.css,frame.css'));
            echo $this->initPageNecessary();
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-my navbar-fixed-top" role="navigation">
            <div class="container-fluid">
                <div class="row headerBox">
                    <div class="col-sm-3 col-md-2">
                        <h2>代码管理</h2>
                    </div>
                    <div class="col-sm-9 col-md-10 sectionTitle">
                        <h2>管理后台</h2>
                    </div>
                </div>
                <div class="row navtoolbarBox">
                    <div class="col-sm-3 col-md-2 user">
                        <p>超级管理员</p>
                    </div>
                    <div class="col-sm-9 col-md-10 breadcrumbs_container">
                        <article class="breadcrumbs"><a class="current">首页</a></article>		
                    </div>
                </div>
            </div>
        </nav>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-3 col-md-2 sidebar hcolumn">
                    dfs
                </div>
                <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 mainBox hcolumn">
                    <?php echo $scriptContent ?>
                </div>
            </div>
        </div>
        <script>
            __wait(function(){
                //操作所有拥有此class的元素等高
                $('.hcolumn').equalHeight(document.body.clientHeight - 36 - 55);
            });
        </script>
        <?php
        echo $this->script()->outputScript($this->assetPath()->getJsOfModule('lab/2.0.3/lab.js,jquery/1.11.1/jquery.min.js,bootstrap/3.3.5/bootstrap.min.js,jquery/ui/base.min.js,jquery/plugin/equalHeight/jquery.equalHeight.js,utility.js'))->lastWait(function() {
            //页面中所有JS加载完毕后才开始执行的
            return '__wait(false, true);';
        });
        ?>        
    </body>
</html>