<!doctype html> 
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title><?php echo $this->headTitle('代码管理')?></title>
        <?php 
            echo $this->headMeta('代码管理', 'keywords')->headMeta('代码管理', 'description');
            echo $this->headLink()->prependStylesheet($this->assetPath()->getCssOfModule('bootstrap/3.3.5/bootstrap.min.css,font-awesome.min.css,jquery/ui/base.min.css,frame.css'));
            echo $this->initPageNecessary();
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-my navbar-fixed-top" role="navigation">
            <div class="container-fluid">
                <div class="row headerBox">
                    <div class="col-sm-3 col-md-2">
                        <h2>代码管理</h2>
                    </div>
                    <div class="col-sm-9 col-md-10 sectionTitle">
                        <h2>管理后台</h2>
                    </div>
                </div>
                <div class="row navtoolbarBox">
                    <div class="col-sm-3 col-md-2 user">
                        <p class="lp"><?php echo $this->loginUserInfo['realname']?></p>
                        <p class="rp"><a href="/auth/logout/"><i class="glyphicon glyphicon-off"></i></a></p>
                    </div>
                    <div class="col-sm-9 col-md-10 breadcrumbs_container">
                        <?php echo $this->breadcrumbs()?>
                    </div>
                </div>
            </div>
        </nav>
        <div class="container-fluid">
            <div class="row">
                <div id="menuId" class="col-sm-3 col-md-2 sidebar">
                    <?php echo $this->getMenuListByUser($this->loginUserInfo)?>
                    <?php echo $this->getProjectListByUser($this->loginUserInfo)?>
                </div>
                <div id="mainId" class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 mainBox">
                    <?php echo $scriptContent ?>
                </div>
            </div>
        </div>
        <script>
            __wait(function(){
                //操作所有拥有此class的元素等高
                $('#menuId').equalHeight(document.body.clientHeight - 85);
                $('#mainId').equalHeight($('#menuId').height() - 5);
                
                //菜单被选中
                $('.PROGRAM-menu_a').on('click', function(){
                    $.setCookie('menuc', this.href);
                });
                $('.PROGRAM-menu_a').each(function(){
                    var url  = $.getCookie('menuc');
                    var wurl = window.location.href;
                    if (this.href == url || this.href == wurl) {
                        $(this).parent().addClass('active');
                    }
                });
                
                // choose text for the show/hide link - can contain HTML (e.g. an image)
                var showText='Show';
                var hideText='Hide';

                // initialise the visibility check
                var is_visible = false;

                // append show/hide links to the element directly preceding the element with a class of "toggle"
                $('.toggle').prev().append(' <a href="#" class="toggleLink">'+hideText+'</a>');

                // hide all of the elements with a class of 'toggle'
                $('.toggle').show();

                // capture clicks on the toggle links
                $('a.toggleLink').click(function() {

                    // switch visibility
                    is_visible = !is_visible;

                    // change the link text depending on whether the element is shown or hidden
                    if ($(this).text()==showText) {
                    $(this).text(hideText);
                    $(this).parent().next('.toggle').slideDown('slow');
                    }
                    else {
                    $(this).text(showText);
                    $(this).parent().next('.toggle').slideUp('slow');
                    }

                    // return false so any link destination is not followed
                    return false;

                });
                
                //页面table表格排序
                $(".tablesorter").tablesorter();
            });
        </script>
        <?php
        echo $this->script()->outputScript($this->assetPath()->getJsOfModule('lab/2.0.3/lab.js,jquery/1.11.1/jquery.min.js,bootstrap/3.3.5/bootstrap.min.js,jquery/ui/base.min.js,jquery/plugin/tablesorter/jquery.tablesorter.min.js,jquery/plugin/equalHeight/jquery.equalHeight.js,plugin/utility.js'))->lastWait(function() {
            //页面中所有JS加载完毕后才开始执行的
            return '__wait(false, true);';
        });
        ?>        
    </body>
</html>